# Generated by Django 3.1.1 on 2020-09-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200907_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Bảo trì'), ('o', 'Đã cho mượn'), ('a', 'Có sẵn'), ('r', 'Chưa có')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
